changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - octocat
  categories:
    - title: "🚀 赛博特性 (Features)"
      labels:
        - feature
        - feat
    - title: "🐛 故障修复 (Bug Fixes)"
      labels:
        - bug
        - fix
    - title: "📦 基础设施 (Maintenance)"
      labels:
        - chore
        - ci
  
  render:
    compact: false
    include_commits: true
